name: song_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pathlib
  - tqdm
  - dill
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - jupyterlab
    - transformers
    - torch==2.1.0 --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - torchaudio --index-url https://download.pytorch.org/whl/cu126
    - tensorboard
    - torchmetrics
    - datasets
    - audiocraft
    - tensorflow
   # - finetune
