name: song_llm
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - tqdm
  - jupyter
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - matplotlib
    - datasets
    - transformers[torch]
    - py_midicsv
    - midi-player